local K = unpack(select(2, ...))
local Module = K:NewModule("Automation")

function Module:OnEnable()
	self:CreateAutoAcceptSummon()
	self:CreateAutoBadBuffs()
	self:CreateAutoBestReward()
	self:CreateAutoDeclineDuels()
	self:CreateAutoDismount()
	self:CreateAutoInvite()
	self:CreateAutoRelease()
	self:CreateAutoResurrect()
	self:CreateAutoTabBinder()
	self:CreateAutoWhisperInvite()
	self:CreateSkipCinematic()
end